name: Run packer build on AWS

on:
  workflow_call:
    inputs:
      debug:
        required: true
        type: number
        default: 0

  push:
    branches: ['main', 'master']
  workflow_dispatch:
    inputs:
      debug:
        description: '1 means debug mode'
        required: true
        type: string
        default: "0"

jobs:
  packer_build:
    runs-on: ubuntu-latest
    name: packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Packer init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: aws-ubuntu.pkr.hcl

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: aws-ubuntu.pkr.hcl
          working_directory: ./

        env:
          PACKER_LOG: 1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
