name: Run packer build on AWS

on:
  workflow_call:
    inputs:
      debug:
        required: true
        type: number
        default: 0

  push:
    branches: ['main', 'master']
  workflow_dispatch:
    inputs:
      debug:
        description: '1 means debug mode'
        required: true
        type: string
        default: "0"
#  schedule:
#    - cron: 0 0 * * *

jobs:
  packer_build:
    runs-on: ubuntu-latest
    name: packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install ansible
        run: pip install ansible

      - name: Install Packer
        run: |
          sudo apt-get update; sudo apt-get install -y curl gnupg software-properties-common ;
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - ;
          sudo apt-add-repository -y "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" ;
          sudo apt-get update && sudo apt-get install -y packer;

      - name: Packer init
        run: |
          make packer-init

      - name: Validate Template
        run: |
          make packer-validate

      - name: Build artifacts
        run: |
          make packer-build
        env:
          PACKER_LOG: ${{ inputs.debug }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1


